name: keep alive

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping URL
        run: |
          curl -fsS https://adtechdocker.onrender.com/index.html
          curl -fsS https://possible-jeannette-actionedge-9b132746.koyeb.app/
