name: keep alive

on:
  schedule:
    - cron: '7,23,37,53 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping URL
        run: |
          curl -fss agreeable-sile-actionedge-2e5ce212.koyeb.app/
#          curl -fsS https://adtechdocker.onrender.com/index.html
#          curl -fsS https://possible-jeannette-actionedge-9b132746.koyeb.app/
